import type { AppData, Project } from "./types";
import { newId } from "./types";

// A realistic demo project so the app is never empty on first run.
const demoProject: Project = {
  id: "demo-smith-residence",
  name: "Smith Residence",
  client: "John & Diane Smith",
  location: "Lake Forest, IL",
  date: "2026-05-30",
  logoUrl: "",
  notes: "Transitional palette — warm neutrals, brass accents, layered textures.",
  items: [
    {
      id: newId(),
      name: "Lawson Tailored Sofa",
      vendor: "Lee Industries",
      category: "Seating",
      room: "Living Room",
      sku: "3935-03",
      price: 4280,
      quantity: 1,
      dimensions: '90"W x 40"D x 33"H',
      material: "Performance linen, down-blend cushions",
      color: "Oatmeal",
      leadTime: "10-12 weeks",
      notes: "COM option available; brass nailhead trim.",
      imageUrl:
        "https://images.unsplash.com/photo-1493663284031-b7e3ac2e6b94?w=900&q=80",
      productUrl: "",
    },
    {
      id: newId(),
      name: "Hand-Knotted Wool Rug",
      vendor: "Loloi",
      category: "Rug",
      room: "Living Room",
      sku: "WYR-04",
      price: 2150,
      quantity: 1,
      dimensions: "9' x 12'",
      material: "Hand-knotted wool",
      color: "Ivory / Sand",
      leadTime: "In stock",
      notes: "Low pile, suitable for high-traffic seating area.",
      imageUrl:
        "https://images.unsplash.com/photo-1600166898405-da9535204843?w=900&q=80",
      productUrl: "",
    },
    {
      id: newId(),
      name: "Sculptural Brass Table Lamp",
      vendor: "Visual Comfort",
      category: "Lighting",
      room: "Living Room",
      sku: "TOB-3920",
      price: 689,
      quantity: 2,
      dimensions: '16"Dia x 27"H',
      material: "Antique brass, linen shade",
      color: "Antique Brass",
      leadTime: "6-8 weeks",
      notes: "Pair flanking the sofa on side tables.",
      imageUrl:
        "https://images.unsplash.com/photo-1543198126-a4f9d9d2f8e2?w=900&q=80",
      productUrl: "",
    },
    {
      id: newId(),
      name: "Round Pedestal Dining Table",
      vendor: "Arteriors",
      category: "Table",
      room: "Dining Room",
      sku: "DR-6612",
      price: 3950,
      quantity: 1,
      dimensions: '54"Dia x 30"H',
      material: "White oak, cerused finish",
      color: "Natural Oak",
      leadTime: "12-14 weeks",
      notes: "Seats six comfortably.",
      imageUrl:
        "https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=900&q=80",
      productUrl: "",
    },
    {
      id: newId(),
      name: "Upholstered Dining Chair",
      vendor: "Bernhardt",
      category: "Seating",
      room: "Dining Room",
      sku: "BH-K1182",
      price: 540,
      quantity: 6,
      dimensions: '22"W x 24"D x 38"H',
      material: "Boucle, oak legs",
      color: "Cream",
      leadTime: "8-10 weeks",
      notes: "",
      imageUrl:
        "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=900&q=80",
      productUrl: "",
    },
    {
      id: newId(),
      name: "Linen Drapery Panels",
      vendor: "The Shade Store",
      category: "Window",
      room: "Primary Bedroom",
      sku: "TSS-LN-09",
      price: 1280,
      quantity: 4,
      dimensions: '50"W x 108"L per panel',
      material: "Belgian linen, cotton lining",
      color: "Flax",
      leadTime: "4-6 weeks",
      notes: "Ripplefold heading, motorized track.",
      imageUrl:
        "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=900&q=80",
      productUrl: "",
    },
  ],
};

export function makeInitialData(): AppData {
  return {
    version: 1,
    projects: [demoProject],
    activeProjectId: demoProject.id,
  };
}
